##############################################################################################################################
# # Cleanup:
#const sleep = ms => () => new Promise((resolve, reject) => window.setTimeout(resolve, ms));
#Promise.resolve()
#.then(() => {  document.getElementsByClassName("details-overlay details-reset position-relative d-inline-block ")[3].children[0].click();  })
#.then(sleep(500))
#.then(() => {  document.getElementsByClassName("dropdown-item btn-link menu-item-danger")[0].click();  })
#.then(sleep(1000))
#.then(() => {  document.getElementsByClassName("btn btn-block btn-danger")[0].click();});
#
# while [ 1 ] ; do sleep 4; xdotool key Up; sleep 0.1; xdotool key Return; done
##############################################################################################################################

name: "Build APK"

permissions:
  contents: write
  actions: write
  
on:
  workflow_dispatch:

env:
  UPLOAD_TAG_NAME: markor
  # REPO_URL: https://github.com/ericyin/markor.git
  # REPO_BRANCH: master 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@v7
      # with:
      #   ref: ${{env.REPO_BRANCH}}

    - name: "Setup: Java"
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: "temurin"

    - name: "Setup: Install additional dependencies"
      run: sudo apt-get install -y ispell

    - name: "Cache: Gradle"
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle
          .gradle
        key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.*') }}

    - name: "Build APK"
      run: |
        echo "make on branch ${{ github.ref_name }}" 
        rm -f Makefile
        mv Makefile2 Makefile
        make clean all FLAVOR=Default     
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV

    - name: "Build: List dist files"
      if: always()
      run: find dist -type f -maxdepth 2

    - name: "Sign APK"
      env:
        KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        # 1. generate temp Keystore cert（valid 2000 days）
        # keytool -genkeypair -v \
        #   -keystore markor.jks \
        #   -alias temp1234 \
        #   -keyalg RSA \
        #   -keysize 2048 \
        #   -validity 2000 \
        #   -storepass temp1234 \
        #   -keypass temp1234 \
        #   -dname "CN=CN, OU=OU, O=O, L=L, S=S, C=C"

        # 2. -maxdepth 3 to search *unsigned.apk
        UNSIGNED_APK=$(find dist -maxdepth 3 -type f -name "*unsigned.apk" | head -n 1)

        # if not found
        if [ -z "$UNSIGNED_APK" ]; then
          echo "❌ error： *unsigned.apk not found in dist fold！"
          exit 1
        fi
        echo "unsigned APK: $UNSIGNED_APK"

        # 3. define signed APK path（use same dir，replace -unsigned with -signed）
        SIGNED_APK="${UNSIGNED_APK/-unsigned/-signed}"

        # 4. search Android build-tools dir
        BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | sort -V | tail -n 1)
        apksigner="$BUILD_TOOLS_DIR/apksigner"
        echo "Using Sign Tool: $apksigner"

        keystore="$RUNNER_TEMP/release.keystore"
        trap 'rm -f "$keystore"' EXIT
        printf '%s' "$KEYSTORE_BASE64" | base64 --decode > "$keystore"  
        keytool -list -v -keystore "$keystore" -alias "$KEY_ALIAS"
             
        "$apksigner" sign \
          --ks "$keystore" \
          --ks-key-alias "$KEY_ALIAS" \
          --ks-pass env:KEYSTORE_PASSWORD \
          --key-pass env:KEY_PASSWORD \
          --out "$SIGNED_APK" \
          "$UNSIGNED_APK"
        "$apksigner" verify --verbose $SIGNED_APK
        echo "signed apk path: $SIGNED_APK"
        echo "SIGNED_APK_PATH=$SIGNED_APK" >> $GITHUB_ENV
        
    - name: "Generate Release Tag"
      id: tag
      run: |
        touch release.txt
        cat <<EOF > release.txt
          🚀 Markor
          ----------------------
          Build Date: ${{ env.FILE_DATE }}
          Branch: ${{ github.ref_name }} 

    - name: "Publish to Release"
      uses: softprops/action-gh-release@v2.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.SIGNED_APK_PATH }}
        release_name: ${{ env.UPLOAD_TAG_NAME }}-${{ env.FILE_DATE }}
        name: ${{ env.UPLOAD_TAG_NAME }}-${{ env.FILE_DATE }}
        tag_name: ${{ env.FILE_DATE }}}
        body_path: release.txt
